print("Hola, bienvenido a tu calculadora de antecesor y secesora de numeros")
numero = int(input("Dime el número del cual deseas saber su numero anterior y posterior "))
anterior = int(numero - 1)
sucesor = int(numero + 1)
print("El numero anterior de ", numero, "es", anterior, "y su número posterior es", sucesor)
